import jsPDF from "jspdf";

export interface ReportData {
  patientName: string;
  patientAge?: number | null;
  patientGender?: string | null;
  date: string;
  bradykinesiaScore: number;
  tremorScore: number;
  rigidityScore: number;
  typingScore: number;
  result: string;
  severity: string;
  confidence: number;
  summary?: string | null;
}

export function generatePdf(data: ReportData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const navy = [12, 35, 64] as const;
  const teal = [45, 138, 158] as const;

  doc.setFillColor(...navy);
  doc.rect(0, 0, 595, 80, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("PDMS Assessment Report", 40, 45);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Parkinson's Disease Detection & Monitoring System", 40, 62);

  let y = 110;
  doc.setTextColor(20, 30, 50);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Patient", 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  y += 18;
  doc.text(`Name: ${data.patientName || "—"}`, 40, y); y += 14;
  doc.text(`Age: ${data.patientAge ?? "—"}    Gender: ${data.patientGender ?? "—"}`, 40, y); y += 14;
  doc.text(`Assessment date: ${data.date}`, 40, y); y += 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Subscores (0–100, higher = more abnormal)", 40, y); y += 8;
  drawBar(doc, "Bradykinesia", data.bradykinesiaScore, 40, y + 12, teal); y += 30;
  drawBar(doc, "Tremor", data.tremorScore, 40, y + 12, teal); y += 30;
  drawBar(doc, "Rigidity", data.rigidityScore, 40, y + 12, teal); y += 30;
  drawBar(doc, "Typing", data.typingScore, 40, y + 12, teal); y += 40;

  doc.setFillColor(245, 248, 250);
  doc.roundedRect(40, y, 515, 90, 8, 8, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Prediction", 56, y + 22);
  doc.setFont("helvetica", "normal");
  doc.text(`Result: ${data.result}`, 56, y + 40);
  doc.text(`Severity: ${data.severity}`, 56, y + 56);
  doc.text(`Confidence: ${data.confidence}%`, 56, y + 72);
  y += 110;

  if (data.summary) {
    doc.setFont("helvetica", "bold");
    doc.text("Clinical summary", 40, y); y += 16;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(data.summary, 515);
    doc.text(lines, 40, y);
    y += lines.length * 13 + 10;
  }

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Disclaimer: This report is generated by an automated screening tool and is NOT a medical diagnosis. Consult a qualified clinician.",
    40, 800, { maxWidth: 515 }
  );

  doc.save(`PDMS-Report-${data.date}.pdf`);
}

function drawBar(doc: jsPDF, label: string, value: number, x: number, y: number, color: readonly [number, number, number]) {
  doc.setFontSize(10);
  doc.setTextColor(20, 30, 50);
  doc.setFont("helvetica", "normal");
  doc.text(`${label}: ${value}`, x, y - 2);
  doc.setFillColor(225, 232, 238);
  doc.roundedRect(x, y + 2, 515, 10, 4, 4, "F");
  const w = Math.max(0, Math.min(100, value)) / 100 * 515;
  doc.setFillColor(color[0], color[1], color[2]);
  doc.roundedRect(x, y + 2, w, 10, 4, 4, "F");
}
